<?php
/**
 * This file is part of AutoEmbed.
 * http://code.google.com/p/autoembed/
 *
 * Some regular expressions found in this file were borrowed 
 * from Karl Benson & Rene-Gilles Deberdt.
 *
 *
 * AutoEmbed is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AutoEmbed is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AutoEmbed.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
  Example:
	array(
		'id' =>					Unique 3 chars comprising A-Z0-9 (must not be any other item with the same ID) eg YTB for YouTube	(Mandatory)
		'title' =>				Title of the Website - shown in the Admin cp for each site as hover link title					(Mandatory)
		'website' =>			Website url (to main site) - used in Admin Cp only										(Mandatory)
		'type' => 'video',		Type of site, must be either video|audio|other										(Mandatory - but defaults to video)
		'plugin' => 'flash',	Type of plugin used by the site either flash|divx|wmp									(Mandatory - but defaults to flash)
		'embed-pattern' =>		[Regex] Match these urls for embedding											(Mandatory)
		'embed-movie' =>			The FINAL embed url, (any flashVars should be added as querystring)						(Mandatory)
								$1 = FULL raw link
								$2, $3... etc are any patterns you specify for parts 
								Note, &ampersands don't need to be encoded. All ampersands in final 'object' are made into &amp;
		'embed-hq-movie' =>		Primarily for youtube. A different link which gives higher quality (but same sizes)				(Optional)
		'embed-width' =>		Width of the embedded object	(don't specify any units, as px is specified later)					(Mandatory)
		'embed-height' =>			Height of the embedded object	(don't specify any units, as px is specified later)					(Mandatory)
	),
*/

global $sites;

$sites = array(
	array(
		'id' => 'ytb',
		'title' => 'YouTube',
		'website' => 'http://www.youtube.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:video\.google\.(?:com|com\.au|co\.uk|de|es|fr|it|nl|pl|ca|cn)/(?:[^"]*?))?(?:(?:www|au|br|ca|es|fr|de|hk|ie|in|il|it|jp|kr|mx|nl|nz|pl|ru|tw|uk)\.)?youtube\.com(?:[^"]*?)?(?:&|&amp;|/|\?|;|\%3F|\%2F)(?:video_id=|v(?:/|=|\%3D|\%2F))([0-9a-z-_]{11})',
		'embed-movie' => 'http://www.youtube.com/v/$2&rel=0&fs=1&rel=0&showsearch=0',
		'embed-hq-movie' => 'http://www.youtube.com/v/$2&ap=%2526fmt%3D18&rel=0',
    'embed-width' => '425',
		'embed-height' => '344',
	),
	array(
		'id' => 'ytp',
		'title' => 'YouTube (Playlists)',
		'website' => 'http://www.youtube.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:(?:www|au|br|ca|es|fr|de|hk|ie|in|il|it|jp|kr|mx|nl|nz|pl|ru|tw|uk)\.)?youtube\.com(?:[^"]*?)?(?:&|&amp;|/|\?|;)(?:id=|p=|p/)([0-9a-f]{16})',
		'embed-movie' => 'http://www.youtube.com/p/$2&rel=0&fs=1',
		'embed-width' => '480',
		'embed-height' => '385',
	),
	array(
		'id' => 'dam',
		'title' => 'Dailymotion',
		'website' => 'http://www.dailymotion.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?dailymotion\.(?:com|alice\.it)/(?:(?:[^"]*?)?video|swf)/([a-z0-9]{1,18})',
		'embed-movie' => 'http://www.dailymotion.com/swf/$2&related=0',
		'embed-width' => '480',
		'embed-height' => '300',
	),
	array(
		'id' => 'ggl',
		'title' => 'Google Video',
		'website' => 'http://video.google.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => 'http://video\.google\.(com|com\.au|co\.uk|de|es|fr|it|nl|pl|ca|cn)/(?:videoplay|url|googleplayer\.swf)\?(?:[^"]*?)?docid=([0-9a-z-_]{1,20})',
		'embed-movie' => 'http://video.google.$2/googleplayer.swf?docId=$3',
		'embed-width' => '400',
		'embed-height' => '326',
	),
	array(
		'id' => 'bbc',
		'title' => 'BBC News (UK Only)',
		'website' => 'http://www.bbc.co.uk/',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://news.bbc.co.uk/[^"]*?/([0-9]{6,9})\.(?:xml|stm))',
		'embed-movie' => 'http://news.bbc.co.uk/player/emp/2_5_4735/player.swf?id=embeddedPlayer_$3&config=http://news.bbc.co.uk/player/emp/config/default.xml?v10&playlist=$2',
		'embed-width' => '512',
		'embed-height' => '323',
	),
	array(
		'id' => 'ipl',
		'title' => 'BBC Iplayer (UK Only)',
		'website' => 'http://www.bbc.co.uk/iplayer',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?bbc\.co\.uk/iplayer/(?:page/item|episode)/([a-z0-9]{8})(?:\.shtml|/)',
		'embed-movie' => 'http://www.bbc.co.uk/emp/player.swf?playlist=http://www.bbc.co.uk/iplayer/playlist/$2&config=http://www.bbc.co.uk/emp/iplayer/config.xml&domId=emp1',
		'embed-width' => '640',
		'embed-height' => '385',
	),
	array(
		'id' => 'mgv',
		'title' => 'MegaVideo',
		'website' => 'http://www.megavideo.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?megavideo\.com/(?:\?(?:[^"]*?)?v=|v/)([0-9a-z]{8})',
		'embed-movie' => 'http://www.megavideo.com/v/$2.0.0',
		'embed-width' => '440',
		'embed-height' => '359',
	),
	array(
		'id' => 'mcf',
		'title' => 'MetaCafe',
		'website' => 'http://www.metacafe.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?metacafe\.com/(?:watch|fplayer)/(\w{1,10})/',
		'embed-movie' => 'http://www.metacafe.com/fplayer/$2/metacafe.swf',
		'embed-width' => '400',
		'embed-height' => '345',
	),
	array(
		'id' => 'veo',
		'title' => 'Veoh',
		'website' => 'http://www.veoh.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?veoh\.com/(?:videos/|videodetails2\.swf\?permalinkId=)([0-9a-z]*)',
		'embed-movie' => 'http://www.veoh.com/veohplayer.swf?permalinkId=$2&id=anonymous&player=videodetailsembedded&videoAutoPlay=0',
		'embed-width' => '460',
		'embed-height' => '345',
	),
	array(
		'id' => 'rev',
		'title' => 'Revver',
		'website' => 'http://www.revver.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:one\.|www\.)?revver\.com/(?:watch|video)/([0-9]{1,8})',
		'embed-movie' => 'http://flash.revver.com/player/1.0/player.swf?mediaId=$2',
		'embed-width' => '480',
		'embed-height' => '392',
	),
	array(
		'id' => 'vimeo',
		'title' => 'Vimeo',
		'website' => 'http://www.vimeo.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?vimeo\.com/([0-9]{1,12})',
		'embed-movie' => 'http://vimeo.com/moogaloop.swf?clip_id=$2&server=vimeo.com&fullscreen=1&show_title=1&show_byline=1&show_portrait=0&color=01AAEA',
		'embed-width' => '400',
		'embed-height' => '302',
	),
	array(
		'id' => '123',
		'title' => '123video',
		'website' => 'http://www.123video.nl',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?123video\.nl/(?:playvideos\.asp\?(?:[^"]*?)?MovieID=|123video_share\.swf\?mediaSrc=)([0-9]{1,8})',
		'embed-movie' => 'http://www.123video.nl/123video_share.swf?mediaSrc=$2',
		'embed-width' => '420',
		'embed-height' => '339',
	),
	array(
		'id' => '5mi',
		'title' => '5min Life Videopedia',
		'website' => 'http://www.5min.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?5min\.com/(?:Embeded/|Video/(?:[0-9a-z_-]*?)?-)([0-9]{8})',
		'embed-movie' => 'http://www.5min.com/Embeded/$2/',
		'embed-width' => '425',
		'embed-height' => '355',
	),
	array(
		'id' => '9yo',
		'title' => '9You',
		'website' => 'http://www.9You.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|v\.)?9you\.com/(?:player|watch)/([0-9a-z]{9})',
		'embed-movie' => 'http://v.9you.com/player/$2',
		'embed-width' => '420',
		'embed-height' => '380',
	),
	array(
		'id' => 'abc',
		'title' => 'ABC News',
		'website' => 'http://www.abcnews.go.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(http://video-cdn\.abcnews\.com/(?:[0-9a-z_-]*?)\.flv)',
		'embed-movie' => 'http://www.archive.org/flow/FlowPlayerLight.swf?config=%7Bembedded%3Atrue%2CshowFullScreenButton%3Atrue%2CshowMuteVolumeButton%3Atrue%2CshowMenu%3Atrue%2CautoBuffering%3Afalse%2CautoPlay%3Afalse%2CinitialScale%3A%27fit%27%2CmenuItems%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%2Ctrue%2Cfalse%5D%2CusePlayOverlay%3Afalse%2CshowPlayListButtons%3Atrue%2CplayList%3A%5B%7Burl%3A%27$2%27%7D%5D%2CcontrolBarGloss%3A%27high%27%2CshowVolumeSlider%3Atrue%2Cloop%3Afalse%2CcontrolBarBackgroundColor%3A%270x808080%27%7D',
		'embed-width' => '480',
		'embed-height' => '388',
	),
	array(
		'id' => 'adu',
		'title' => 'AdultSwim',
		'website' => 'http://www.adultswim.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://www\.adultswim\.com/video/(?:vplayer/index\.html\?id=|\?episodeID=|ASVPlayer\.swf\?id=)([0-9a-f]{32})',
		'embed-movie' => 'http://www.adultswim.com/video/ASVPlayer.swf?id=$2',
		'embed-width' => '425',
		'embed-height' => '355',
	),
	array(
		'id' => 'ani',
		'title' => 'AniBoom',
		'website' => 'http://www.aniboom.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|api\.)?aniboom\.com/(?:Player.aspx\?(?:[^"]*?)?v=|video/|e/)([0-9]{1,10})',
		'embed-movie' => 'http://api.aniboom.com/e/$2',
		'embed-width' => '425',
		'embed-height' => '355',
	),
	array(
		'id' => 'aol',
		'title' => 'AOL Uncut',
		'website' => 'http://uncutvideo.aol.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://uncutvideo(?:\.latino)?\.aol\.(?:com|es|it|de|co\.uk|nl|fr|ca|ie|se|pl))/videos/([0-9a-f]{30,33})',
		'embed-movie' => 'http://uncutvideo.aol.com/v7.310/en-US/uc_videoplayer.swf?aID=$3&site=$2/',
		'embed-width' => '415',
		'embed-height' => '347',
	),
	array(
		'id' => 'arc',
		'title' => 'Archive.org',
		'website' => 'http://www.archive.org',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?archive\.org/download/((?:[0-9a-z_-]*?)/(?:[0-9a-z_-]*?)\.flv)',
		'embed-movie' => 'http://www.archive.org/flow/FlowPlayerLight.swf?config=%7Bembedded%3Atrue%2CshowFullScreenButton%3Atrue%2CshowMuteVolumeButton%3Atrue%2CshowMenu%3Atrue%2CautoBuffering%3Afalse%2CautoPlay%3Afalse%2CinitialScale%3A%27fit%27%2CmenuItems%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%2Ctrue%2Cfalse%5D%2CusePlayOverlay%3Afalse%2CshowPlayListButtons%3Atrue%2CplayList%3A%5B%7Burl%3A%27$2%27%7D%5D%2CcontrolBarGloss%3A%27high%27%2CshowVolumeSlider%3Atrue%2CbaseURL%3A%27http%3A%2F%2Fwww%2Earchive%2Eorg%2Fdownload%2F%27%2Cloop%3Afalse%2CcontrolBarBackgroundColor%3A%270x000000%27%7D',
		'embed-width' => '480',
		'embed-height' => '360',
	),
	array(
		'id' => 'ato',
		'title' => 'Atom',
		'website' => 'http://www.atom.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(http://media\.mtvnservices\.com/mgid:hcx:content:atom\.com:(?:(?:[0-9a-z]{8})(?:(?:-(?:[0-9a-z]{4})){3})-(?:[0-9a-z]{12})))',
		'embed-movie' => '$2',
		'embed-width' => '425',
		'embed-height' => '354',
	),
	array(
		'id' => 'beb',
		'title' => 'Bebo',
		'website' => 'http://www.bebo.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://bebo\.(?:[0-9]{1,4})\.download\.videoegg\.com(?:(?:/(?:[0-9a-z]*)){5}))',
		'embed-movie' => 'http://static.videoegg.com/videoegg/loader.swf?file=$2',
		'embed-width' => '425',
		'embed-height' => '350',
	),
	array(
		'id' => 'bli',
		'title' => 'Blip',
		'website' => 'http://www.blip.tv',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|(?:[a-z0-9]*?)\.)?blip\.tv/play/(\w{1,15})',
		'embed-movie' => 'http://blip.tv/play/$2',
		'embed-width' => '320',
		'embed-height' => '270',
	),
	array(
		'id' => 'bof',
		'title' => 'BoFunk',
		'website' => 'http://www.bofunk.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://www.bofunk.com/e/(?:[0-9a-z]{39}))',
		'embed-movie' => '$2',
		'embed-width' => '446',
		'embed-height' => '370',
	),
	array(
		'id' => 'boo',
		'title' => 'BooMp3',
		'website' => 'http://www.boomp3.com',
		'type' => 'audio',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|static\.)?boomp3\.com/(?:listen/|player\.swf\?song=)([0-9a-z_-]{11})',
		'embed-movie' => 'http://static.boomp3.com/player.swf?song=$2&noinfo=1',
		'embed-width' => '200',
		'embed-height' => '20',
	),
	array(
		'id' => 'bre',
		'title' => 'Break (SEO Style)',
		'website' => 'http://www.break.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://embed\.break\.com/(?:[0-9a-z]{8}))',
		'embed-movie' => '$2',
		'embed-width' => '464',
		'embed-height' => '392',
	),
	array(
		'id' => 'brk',
		'title' => 'Break (User Content)',
		'website' => 'http://www.break.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://embed\.break\.com/(?:[0-9a-z]{8}))',
		'embed-movie' => '$2',
		'embed-width' => '464',
		'embed-height' => '392',
	),
	array(
		'id' => 'bri',
		'title' => 'Brightcove.com',
		'website' => 'http://link.brightcove.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => 'http://link\.brightcove\.com/services/link/bcpid([0-9]+)/bctid([0-9]+)',
		'embed-movie' => 'http://services.brightcove.com/services/viewer/federated_f8/$2?videoId=$3&playerId=$2&viewerSecureGatewayURL=https://console.brightcove.com/services/amfgateway&servicesURL=http://services.brightcove.com/services&cdnURL=http://admin.brightcove.com&domain=embed&autoStart=false&',
		'embed-width' => '486',
		'embed-height' => '412',
	),
	array(
		'id' => 'brt',
		'title' => 'Brightcove.tv',
		'website' => 'http://www.brightcove.tv',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?brightcove\.tv/title.jsp\?(?:[^"]*?)?title=([0-9]{1,12})',
		'embed-movie' => 'http://www.brightcove.tv/playerswf?allowFullScreen=true&initVideoId=$2&servicesURL=http://www.brightcove.tv&viewerSecureGatewayURL=https://www.brightcove.tv&cdnURL=http://admin.brightcove.com&autoStart=false',
		'embed-width' => '486',
		'embed-height' => '412',
	),
	array(
		'id' => 'bro',
		'title' => 'Broadcaster',
		'website' => 'http://www.broadcaster.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?broadcaster\.com/video/external/player\.swf\?clip=([0-9a-z_-]*?)\.flv)',
		'embed-movie' => '$2',
		'embed-width' => '425',
		'embed-height' => '340',
	),
	array(
		'id' => 'car',
		'title' => 'CarPix Tv',
		'website' => 'http://carpixtv.vidiac.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://carpixtv\.vidiac\.com/video/((?:[0-9a-z]{8})(?:(?:-(?:[0-9a-z]{4})){3})-(?:[0-9a-z]{12}))\.htm',
		'embed-movie' => 'http://carpixtv.vidiac.com/vidiac.swf?video=$2',
		'embed-width' => '428',
		'embed-height' => '352',
	),
	array(
		'id' => 'cel',
		'title' => 'Cellfish',
		'website' => 'http://www.cellfish.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(cellfish\.|www\.)?cellfish\.com/(?:video|ringtone|multimedia)/([0-9]{1,10})/',
		'embed-movie' => 'http://$2cellfish.com/static/swf/player8.swf?Id=$3',
		'embed-width' => '420',
		'embed-height' => '315',
	),
	array(
		'id' => 'cla',
		'title' => 'Clarin',
		'website' => 'http://www.videos.clarin.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)videos\.clarin\.com/index\.html\?id=([0-9]{1,12})',
		'embed-movie' => 'http://www.clarin.com/shared/v9/swf/clarinvideos/player.swf?id=$2&RUTAS=http://www.clarin.com/shared/v9/swf/clarinvideos/rutas.xml&SEARCH=http://www.servicios.clarin.com/decoder/buscador_getMtmYRelacionados/$2|CLARIN_VIDEOS|VIDEO|null|100|1|10|null.xml',
		'embed-width' => '533',
		'embed-height' => '438',
	),
	array(
		'id' => 'cli',
		'title' => 'Clip.vn',
		'website' => 'http://www.clip.vn',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?clip\.vn/w(?:atch/(?:[a-z0-9-_]*?))?/([a-z0-9_-]{1,5}),vn',
		'embed-movie' => 'http://www.clip.vn/w/$2,vn,0,,hq',
		'embed-width' => '448',
		'embed-height' => '361',
	),
	array(
		'id' => 'clo',
		'title' => 'ClipFish (Old)',
		'website' => 'http://www.clipfish.de',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?clipfish\.de/(?:(?:player\.php|videoplayer\.swf)\?(?:[^"]*?)?vid=|video/)([0-9]{1,20})',
		'embed-movie' => 'http://www.clipfish.de/videoplayer.swf?as=0&vid=$2&r=1',
		'embed-width' => '464',
		'embed-height' => '380',
	),
	array(
		'id' => 'cln',
		'title' => 'ClipFish (New)',
		'website' => 'http://www.clipfish.de',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?clipfish\.de/(?:video)?player\.(?:swf|php)(?:[^"]*?)videoid=((?:[a-z0-9]{18})(?:==)?|(?:[a-z0-9]{6})(?:==)?)',
		'embed-movie' => 'http://www.clipfish.de/videoplayer.swf?as=0&videoid=$2%3D%3D&r=1',
		'embed-width' => '464',
		'embed-height' => '380',
	),
	array(
		'id' => 'clj',
		'title' => 'ClipJunkie',
		'website' => 'http://www.clipjunkie.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?clipjunkie\.com/((?:[^"]*?)-vid(?:[0-9]{1,10}))\.html',
		'embed-movie' => 'http://www.clipjunkie.com/flvplayer/flvplayer.swf?flv=http://videos.clipjunkie.com/videos/$2.flv&themes=http://www.clipjunkie.com/flvplayer/themes.xml&playList=http://www.clipjunkie.com/playlist.php&config=http://www.clipjunkie.com/skin/config.xml',
		'embed-width' => '460',
		'embed-height' => '357',
	),
	array(
		'id' => 'cll',
		'title' => 'ClipLife',
		'website' => 'http://www.cliplife.jp',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?cliplife\.jp/clip/\?content_id=([0-9a-z_-]{6,12})',
		'embed-movie' => 'http://player.cliplife.jp/player_external_03.swf?clipinfo=http%3A%2F%2Fstream.cliplife.jp%2Fclipinfo%2Fclipinfo_03.php%3Fcontent_id%3D$2',
		'embed-width' => '320',
		'embed-height' => '264',
	),
	array(
		'id' => 'clm',
		'title' => 'ClipMoon',
		'website' => 'http://www.clipmoon.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?clipmoon\.com/(?:videos/|(?:[^"]*?)viewkey=)([0-9a-z]{1,10})',
		'embed-movie' => 'http://www.clipmoon.com/flvplayer.swf?config=http://www.clipmoon.com/flvplayer.php?viewkey=$2&external=yes',
		'embed-width' => '460',
		'embed-height' => '357',
	),
	array(
		'id' => 'cls',
		'title' => 'Clipser',
		'website' => 'http://www.clipser.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?clipser\.com/(?:Play\?vid=|watch_video/)([0-9]{4,10})',
		'embed-movie' => 'http://www.clipser.com/Play?vid=$2',
		'embed-width' => '425',
		'embed-height' => '355',
	),
	array(
		'id' => 'clk',
		'title' => 'ClipShack',
		'website' => 'http://www.clipshack.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?clipshack\.com/Clip\.aspx\?key=([0-9a-f]{16})',
		'embed-movie' => 'http://www.clipshack.com/player.swf?key=$2',
		'embed-width' => '430',
		'embed-height' => '370',
	),
	array(
		'id' => 'col',
		'title' => 'Cold-Link',
		'website' => 'http://www.cold-link.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?cold-link\.com/(?:play|vid)/([a-z0-9]{8,12})',
		'embed-movie' => 'http://cold-link.com/vid/$2',
		'embed-width' => '575',
		'embed-height' => '400',
	),
	array(
		'id' => 'clg',
		'title' => 'CollegeHumor',
		'website' => 'http://www.collegehumour.com',
		'type' => 'video',
		'plugin' => 'flash',
		'title' => 'CollegeHumor',
		'embed-pattern' => 'http://(?:www\.)?collegehumor\.com/video:([0-9]{1,12})',
		'embed-movie' => 'http://www.collegehumor.com/moogaloop/moogaloop.swf?clip_id=$2',
		'embed-width' => '480',
		'embed-height' => '360',
	),
	array(
		'id' => 'coc',
		'title' => 'ComedyCentral(Inc. TheDailyShow)',
		'website' => 'http://www.comedycentral.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?(?:comedycentral|thedailyshow)\.com/(?:[a-z0-9]{5,20}/)?video(?:s)?(?:/index)?\.jhtml\?videoId=([0-9]{1,10})',
		'embed-movie' => 'http://www.comedycentral.com/sitewide/video_player/view/default/swf.jhtml?videoId=$2',
		'embed-width' => '332',
		'embed-height' => '316',
	),
	array(
		'id' => 'cra',
		'title' => 'Crackle',
		'website' => 'http://www.crackle.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?crackle\.com/c/([a-z0-9_]*?)/([a-z0-9_]*?)/([0-9]{1,10})',
		'embed-movie' => 'http://www.crackle.com/p/$2/$3.swf?id=$4',
		'embed-width' => '400',
		'embed-height' => '328',
	),
	array(
		'id' => 'cru',
		'title' => 'CrunchyRoll',
		'website' => 'http://www.crunchyroll.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?crunchyroll\.com/getitem\?ih=([0-9a-z]{19})&(?:amp;)?videoid=([0-9]{1,12})&(?:amp;)?mediaid=([0-9]{1,12})&(?:amp;)?hash=([0-9a-z]{19})',
		'embed-movie' => ' http://www.crunchyroll.com/flash/20080910153703.043ec803b06cc356a1e15c1184831a24/oldplayer2.swf?file=http%3A%2F%2Fwww.crunchyroll.com%2Fgetitem%3Fih%3D$2%26videoid%3D$3%26mediaid%3D$4%26hash%3D$5&autostart=false',
		'embed-width' => '576',
		'embed-height' => '325',
	),
	array(
		'id' => 'cur',
		'title' => 'Current',
		'website' => 'http://www.current.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?current\.com/e/(?:[0-9]{8}))',
		'embed-movie' => '$2',
		'embed-width' => '400',
		'embed-height' => '400',
	),
	array(
		'id' => 'dah',
		'title' => 'Dailyhaha',
		'website' => 'http://www.dailyhaha.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?dailyhaha\.com/_vids/(?:Whohah\.swf\?Vid=)?([a-z0-9_-]*?)\.(?:htm|flv)',
		'embed-movie' => 'http://www.dailyhaha.com/_vids/Whohah.swf?Vid=$2.flv',
		'embed-width' => '425',
		'embed-height' => '350',
),
	array(
		'id' => 'dav',
		'title' => 'Dave.tv',
		'website' => 'http://www.dave.tv',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?dave\.tv/MediaPlayer.aspx\?(?:[^"]*?)?contentItemId=([0-9]{1,10})',
		'embed-movie' => 'http://dave.tv/dbox/dbox_small.swf?configURI=http://dave.tv/dbox/config.ashx&volume=50&channelContentId=$2',
		'embed-width' => '300',
		'embed-height' => '260',
	),
	array(
		'id' => 'dee',
		'title' => 'Deezer',
		'website' => 'http://www.deezer.com',
		'type' => 'audio',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?deezer\.com/track/([0-9]{1,12})',
		'embed-movie' => 'http://www.deezer.com/embedded/small-widget-v2.swf?idSong=$2&colorBackground=0x525252&textColor1=0xFFFFFF&colorVolume=0x39D1FD&autoplay=0',
		'embed-width' => '220',
		'embed-height' => '55',
	),
	array(
		'id' => 'dot',
		'title' => 'DotSub (w/o Captions)',
		'website' => 'http://www.dotsub.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?dotsub\.com/(?:media/|view/)((?:[0-9a-z]{8})(?:(?:-(?:[0-9a-z]{4})){3})-(?:[0-9a-z]{12}))',
		'embed-movie' => 'http://dotsub.com/static/players/embed8l.swf?mediauri=http://dotsub.com/media/$2/em/flv/en',
		'embed-width' => '480',
		'embed-height' => '392',
	),
	array(
		'id' => 'dbl',
		'title' => 'DoubleViking',
		'website' => 'http://www.doubleviking.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://doubleviking\.cachefly\.net/videos/doubleviking/(?:[0-9]{4})/(?:[0-9]{1,2})/(?:[0-9]{1,2})/(?:[0-9a-z-]*?)\.flv)',
		'embed-movie' => 'http://www.doubleviking.com/mediaplayer.swf?file=$2',
		'embed-width' => '400',
		'embed-height' => '340',
	),
	array(
		'id' => 'dro',
		'title' => 'Dropshots',
		'website' => 'http://www.dropshots.com',
		'type' => 'video',
		'plugin' => 'flash',
		'title' => 'dropshots.com',
		'embed-pattern' => '(http://media(?:[0-9]{0,2})\.dropshots\.com/photos(?:(?:/(?:[0-9]{1,10})){1,3})\.flv)',
		'embed-movie' => 'http://www.dropshots.com/dropshotsplayer.swf?url=$2',
		'embed-width' => '480',
		'embed-height' => '385',
	),
	array(
		'id' => 'dvo',
		'title' => 'Dv.ouou',
		'website' => 'http://dv.ouou.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://dv\.ouou\.com/(?:play/v_|v/)([a-f0-9]{14})',
		'embed-movie' => 'http://dv.ouou.com/v/$2',
		'embed-width' => '480',
		'embed-height' => '385',
	),
	array(
		'id' => 'dvs',
		'title' => 'Divshare',
		'website' => 'http://www.divshare.com',
		'type' => 'audio',
		'added' => '5.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://www\.divshare\.com/download/([^"]*?)',
		'embed-movie' => 'http://www.divshare.com/flash/playlist?myId=$2',
		'embed-width' => '335',
		'embed-height' => '85',
	),
	array(
		'id' => 'eas',
		'title' => 'EASportsWorld',
		'website' => 'http://www.easportsworld.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://videocdn\.easw\.easports\.com/easportsworld/media/(?:[0-9]{1,12})/(?:[0-9a-z-_]*?)\.flv)',
		'embed-movie' => 'http://ll-999.ea.com/sonet-easw/2.2.4.0/flash/sw/videos/mediaplayer.swf?file=$2&image=http://ll-999.ea.com/sonet-easw/2.2.4.0/images/sw/videos/preview.jpg&backcolor=0x000000&frontcolor=0x006BCC&lightcolor=0x006BCC',
		'embed-width' => '566',
		'embed-height' => '355',
	),
	array(
		'id' => 'eba',
		'title' => 'EbaumsWorld Audio',
		'website' => 'http://www.ebaumsworld.com/audio/',
		'type' => 'audio',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(?:http://www\.ebaumsworld\.com/mediaplayer\.swf\?file=)?(http://media\.ebaumsworld\.com/(?:mediaFiles/)?(?:audio/(?!play/)|(?:[0-9/]{8}))(?:[0-9a-z_-]*?)/(?:[0-9a-z_-]*?)\.mp3)',
		'embed-movie' => 'http://www.ebaumsworld.com/mediaplayer.swf?file=$2&showeq=true&displayheight=50',
		'embed-width' => '440',
		'embed-height' => '70',
	),
	array(
		'id' => 'ebv',
		'title' => 'EbaumsWorld Videos',
		'website' => 'http://www.ebaumsworld.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(?:http://www\.ebaumsworld\.com/mediaplayer\.swf\?file=)?(http://media\.ebaumsworld\.com/mediaFiles/video/(?:[0-9]{1,12})/(?:[0-9]{1,12})\.flv)',
		'embed-movie' => 'http://www.ebaumsworld.com/mediaplayer.swf?file=$2',
		'embed-width' => '425',
		'embed-height' => '345',
	),
	array(
		'id' => 'esp',
		'title' => 'ESPN',
		'website' => 'http://www.espn.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://sports\.espn\.go\.com/broadband/(?:player\.swf\?mediaId=|video/videopage\?(?:[^"]*?)?videoId=)([0-9]{1,10})',
		'embed-movie' => 'http://sports.espn.go.com/broadband/player.swf?mediaId=$2',
		'embed-width' => '440',
		'embed-height' => '361',
	),
	array(
		'id' => 'fod',
		'title' => 'FunnyOrDie',
		'website' => 'http://www.funnyordie.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|www2\.)?funnyordie\.com/(?:videos/|public/flash/fodplayer\.swf\?key=)([0-9a-z]{8,12})',
		'embed-movie' => 'http://www2.funnyordie.com/public/flash/fodplayer.swf?key=$2',
		'embed-width' => '464',
		'embed-height' => '388',
	),
	array(
		'id' => 'g4t',
		'title' => 'G4TV',
		'website' => 'http://www.g4tv.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?g4tv\.com/(?:xplay/videos/|lv3/|sv3/)([0-9]{1,10})',
		'embed-movie' => 'http://www.g4tv.com/lv3/$2',
		'embed-width' => '480',
		'embed-height' => '418',
	),
	array(
		'id' => 'gko',
		'title' => 'GameKyo',
		'website' => 'http://www.gamekyo.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?gamekyo\.com/(?:video|flash/flvplayer\.swf\?videoid=)([0-9]{1,8})',
		'embed-movie' => 'http://www.gamekyo.com/flash/flvplayer.swf?videoid=$2',
		'embed-width' => '512',
		'embed-height' => '307',
),
	array(
		'id' => 'gam',
		'title' => 'GameSpot',
		'website' => 'http://www.gamespot.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:(?:[a-z]*?)\.)?gamespot\.com/(?:[^"]*?)video/(?:(?:[0-9]{1,12})/)?([0-9]{1,12})',
		'embed-movie' => 'http://image.com.com/gamespot/images/cne_flash/production/media_player/proteus/one/proteus2.swf?playerMode=embedded&movieAspect=4.3&flavor=EmbeddedPlayerVersion&skin=http://image.com.com/gamespot/images/cne_flash/production/media_player/proteus/one/skins/gamespot.png&paramsURI=http%3A%2F%2Fwww.gamespot.com%2Fpages%2Fvideo_player%2Fxml.php%3Fid%3D$2%26mode%3Dembedded%26width%3D432%26height%3D362',
		'embed-width' => '432',
		'embed-height' => '362',
),
	array(
		'id' => 'gat',
		'title' => 'GameTrailers (Inc. User Movies)',
		'website' => 'http://www.gametrailers.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?gametrailers\.com/(?:player/(u)?(?:sermovies/)?|remote_wrap\.php\?(u)?mid=)([0-9]{1,10})',
		'embed-movie' => 'http://www.gametrailers.com/remote_wrap.php?$2$3mid=$4', //Either $2 or $3 will be empty
		'embed-width' => '480',
		'embed-height' => '392',
	),
	array(
		'id' => 'gab',
		'title' => 'GameTube',
		'website' => 'http://www.gametube.org',
		'type' => 'video',
		'plugin' => 'flash',
		'title' => 'Gametube.org',
		'embed-pattern' => 'http://(?:www\.)?gametube\.org/(?:\#/video/|htmlVideo\.jsp\?id=|miniPlayer\.swf\?vidId=)((?:[0-9a-z]{1,3})/(?:[a-z0-9_-]{26})=)',
		'embed-movie' => 'http://www.gametube.org/miniPlayer.swf?vidId=$2',
		'embed-width' => '425',
		'embed-height' => '335',
	),
	array(
		'id' => 'gav',
		'title' => 'GameVideos.1up',
		'website' => 'http://www.gamevideos.1up.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?gamevideos(?:\.1up)?\.com/(?:video/id/|video/embed\?(?:[^"]*?)?video=)([0-9]{1,8})',
		'embed-movie' => 'http://gamevideos.1up.com/swf/gamevideos11.swf?embedded=1&fullscreen=1&autoplay=0&src=http://gamevideos.1up.com/video/videoListXML%3Fid%3D$2%26adPlay%3Dfalse',
		'embed-width' => '500',
		'embed-height' => '319',
	),
	array(
		'id' => 'gar',
		'title' => 'GarageTv',
		'website' => 'http://www.garagetv.be',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://www\.garagetv\.be/v/(?:[0-9a-z-\!_]*?)/v\.aspx)',
		'embed-movie' => '$2',
		'embed-width' => '430',
		'embed-height' => '369',
  ),
	array(
		'id' => 'glo',
		'title' => 'Gloria',
		'website' => 'http://www.gloria.tv',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?gloria\.tv/\?video=([a-z0-9]{20})',
		'embed-movie' => 'http://www.gloria.tv/flvplayer.swf?file=http%3A%2F%2Fwww.gloria.tv%2F%3Fembed%26video%3D$2%26width%3D512%26height%3D288&type=flv&image=http%3A%2F%2Fwww.gloria.tv%2F%3Fembed%26image%3D$2%26width%3D512%26height%3D288&autostart=false&showdigits=true&usefullscreen=false&logo=http%3A%2F%2Fwww.gloria.tv%2Fimage%2Flogo_embed.png&link=http%3A%2F%2Fwww.gloria.tv%2F%3Fvideo%3Dddexrl6eelym3gaabxmz%26amp%3Bview%3Dflash&linktarget=_blank&volume=100&backcolor=0xe0e0e0&frontcolor=0x000000&lightcolor=0xf00000',
		'embed-width' => '512',
		'embed-height' => '404',
	),
	array(
		'id' => 'goe',
		'title' => 'GoEar',
		'website' => 'http://www.goear.com',
		'type' => 'audio',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?goear\.com/listen\.php\?v=([a-z0-9]{7})',
		'embed-movie' => 'http://www.goear.com/files/external.swf?file=$2',
		'embed-width' => '353',
		'embed-height' => '132',
	),
	array(
		'id' => 'glu',
		'title' => 'Glumbert',
		'website' => 'http://www.glumbert.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?glumbert\.com/(?:embed|media)/([a-z0-9_-]{1,30})',
		'embed-movie' => 'http://www.glumbert.com/embed/$2',
		'embed-width' => '425',
		'embed-height' => '335',
	),
	array(
		'id' => 'god',
		'title' => 'GodTube',
		'website' => 'http://www.godtube.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?godtube\.com/view_video\.php\?(?:[^"]*?)?viewkey=([0-9a-f]{20})',
		'embed-movie' => 'http://godtube.com/flvplayer.swf?viewkey=$2',
		'embed-width' => '330',
		'embed-height' => '270',
	),
	array(
		'id' => 'gof',
		'title' => 'GoFish (Videos)',
		'website' => 'http://www.gofish.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?gofish\.com/player(?:\.gfp\?|/fwplayer\.swf\?(?:[^"]*?))gfid=([0-9-]{10})',
		'embed-movie' => 'http://www.gofish.com/player/fwplayer.swf?loc=blog&gf=true&ns=false&fs=false&gfid=$2&c=grey&autoPlay=false&getAd=false&wm=false&ct=true&tb=false&svr=www.gofish.com',
		'embed-width' => '448',
		'embed-height' => '336',
	),
	array(
		'id' => 'gov',
		'title' => 'GoFish (Channels)',
		'website' => 'http://www.gofish.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?gofish\.com/(?:channel\.gfp|player/gfplayer\.swf)(?:\?gfid|(?:[^"]*?)cgfid)=([0-9-]{7})(?:[^"]*?)(?:videogfid|vgfid)=([0-9-]{10})',
		'embed-movie' => 'http://www.gofish.com/player/GFPlayer.swf?cm=false&tb=true&ap=false&co=false&ct=true&gf=true&loc=external&lp=true&sb=true&cgfid=$2&pgfid&vgfid=$3&ad=false&svr=www.gofish.com',
		'embed-width' => '492',
		'embed-height' => '336',
	),
	array(
		'id' => 'got',
		'title' => 'GotGame',
		'website' => 'http://www.gotgame.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(http://tv\.gotgame\.com/flvideo/(?:[0-9]{1,10})\.flv)',
		'embed-movie' => 'http://tv.gotgame.com/player/FlowPlayerDark.swf?config=%7Bembedded%3Atrue%2CshowFullScreenButton%3Atrue%2CshowMuteVolumeButton%3Atrue%2CshowMenu%3Atrue%2CautoBuffering%3Afalse%2CautoPlay%3Afalse%2CinitialScale%3A%27fit%27%2CmenuItems%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%2Ctrue%2Cfalse%5D%2CusePlayOverlay%3Afalse%2CshowPlayListButtons%3Atrue%2CplayList%3A%5B%7Burl%3A%27$2%27%7D%5D%2CcontrolBarGloss%3A%27high%27%2CshowVolumeSlider%3Atrue%2Cloop%3Afalse%2CcontrolBarBackgroundColor%3A%270x808080%27%7D',
		'embed-width' => '516',
		'embed-height' => '320',
	),
	array(
		'id' => 'gra',
		'title' => 'GrassRoots ItvLocal',
		'website' => 'http://grassroots.itvlocal.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://grassroots\.itvlocal\.com/(?:Clip\.aspx|player\.swf)\?key=([a-f0-9]{16})',
		'embed-movie' => 'http://grassroots.itvlocal.com/player.swf?key=$2',
		'embed-width' => '430',
		'embed-height' => '370',
	),
	array(
		'id' => 'gri',
		'title' => 'GrindTv',
		'website' => 'http://www.grindtv.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://images\.grindtv\.com/images/player/videoplayer\.swf\?(?:[^"]*?)i=(?:[0-9]{1,12}))',
		'embed-movie' => '$2',
		'embed-width' => '640',
		'embed-height' => '480',
	),
	array(
		'id' => 'gub',
		'title' => 'Guba',
		'website' => 'http://www.guba.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?guba\.com/watch/([0-9]{1,12})',
		'embed-movie' => 'http://www.guba.com/f/root.swf?video_url=http://free.guba.com/uploaditem/$2/flash.flv&isEmbeddedPlayer=true',
		'embed-width' => '525',
		'embed-height' => '360',
	),
	array(
		'id' => 'hub',
		'title' => 'TheHub',
		'website' => 'http://hub.witness.org',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://hub\.witness\.org/(?:en|fr|es)/node/([0-9]{1,10})',
		'embed-movie' => 'http://hub.witness.org/sites/hub.witness.org/modules/contrib-5/flvmediaplayer/mediaplayer.swf?file=http://hub.witness.org/xspf/node/$2&overstretch=fit&repeat=false&logo=http://hub.witness.org/sites/hub.witness.org/themes/witness/images/hub_wm.png',
		'embed-width' => '320',
		'embed-height' => '260',
	),
	array(
		'id' => 'hul',
		'title' => 'Hulu (Usa Only)',
		'website' => 'http://www.hulu.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?hulu\.com/embed/(?:[a-z0-9-_]{10,32}))',
		'embed-movie' => '$2',
		'embed-width' => '512',
		'embed-height' => '296',
	),
	array(
		'id' => 'hum',
		'title' => 'Humour',
		'website' => 'http://www.humour.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://video\.humour\.com/videos-comiques/videos/([0-9a-f]{32})\.flv',
		'embed-movie' => 'http://www.humour.com/videos-comiques/player/mediaplayer.swf?file=http://video.humour.com/videos-comiques/videos/$2.flv&http://video.humour.com/videos-comiques/printscreen/large/$2.jpg',
		'embed-width' => '425',
		'embed-height' => '355',
	),
	array(
		'id' => 'iua',
		'title' => 'Video.i.ua',
		'website' => 'http://video.i.ua',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(http://i1\.i\.ua/video/vp3\.swf\?9&(?:amp;)?userID=(?:[0-9]{1,20})&(?:amp;)?videoID=(?:[0-9]{1,20})&(?:amp;)?playTime=(?:[0-9]{1,20})&(?:amp;)?repeat=0&(?:amp;)?autostart=0&(?:amp;)?videoSize=(?:[0-9]{1,20})&(?:amp;)?userStatus=(?:[0-9]{1,2})&(?:amp;)?notPreview=(?:[0-9]{1,2})&(?:amp;)?mID=m?(?:[0-9]{1,2}))',
		'embed-movie' => '$2',
		'embed-width' => '450',
		'embed-height' => '349',
	),
	array(
		'id' => 'ign',
		'title' => 'IGN',
		'website' => 'http://www.ign.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:(?:(?:[a-z0-9]*?)\.){0,3})ign\.com/(?:[a-z0-9-_]*?)?/objects/([0-9]{1,10})/(?:(?:[a-z0-9-_]*?)/)?videos/',
		'embed-movie' => 'http://videomedia.ign.com/ev/ev.swf?object_ID=$2',
		'embed-width' => '433',
		'embed-height' => '360',
	),
	array(
		'id' => 'iji',
		'title' => 'iJigg',
		'website' => 'http://www.ijigg.com',
		'type' => 'audio',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?ijigg\.com/(?:jiggPlayer\.swf\?songID=|songs/|trackback/)([0-9A-Z]{9,12})',
		'embed-movie' => 'http://www.ijigg.com/jiggPlayer.swf?songID=$2&Autoplay=0',
		'embed-width' => '315',
		'embed-height' => '80',
	),
	array(
		'id' => 'imd',
		'title' => 'IMDB',
		'website' => 'http://www.imdb.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?totaleclips\.com/Player/Bounce\.aspx\?eclipid=([0-9a-z]{1,12})&(?:amp;)?bitrateid=([0-9]{1,10})&(?:amp;)?vendorid=([0-9]{1,10})&(?:amp;)?type=\.flv',
		'embed-movie' => 'http://www.imdb.com/images/js/app/video/mediaplayer.swf?file=http%3A%2F%2Fwww.totaleclips.com%2FPlayer%2FBounce.aspx%3Feclipid%3D$2%26bitrateid%3D$3%26vendorid%3D$4%26type%3D.flv&backcolor=0x000000&frontcolor=0xCCCCCC&lightcolor=0xFFFFCC&shuffle=false&autostart=false',
		'embed-width' => '480',
		'embed-height' => '380',
	),
	array(
		'id' => 'imm',
		'title' => 'Imeem (Music)',
		'website' => 'http://www.imeem.com',
		'type' => 'audio',
		'plugin' => 'flash',
		'embed-pattern' => '(http://media\.imeem\.com/m/(?:[0-9a-z_-]{10}))',
		'embed-movie' => '$2/aus=false/',
		'embed-width' => '300',
		'embed-height' => '110',
	),
	array(
		'id' => 'imp',
		'title' => 'Imeem (Playlists)',
		'website' => 'http://www.imeem.com',
		'type' => 'other',
		'plugin' => 'flash',
		'embed-pattern' => '(http://media\.imeem\.com/pl/(?:[0-9a-z_-]{10}))',
		'embed-movie' => '$2/aus=false/',
		'embed-width' => '460',
		'embed-height' => '390',
	),
	array(
		'id' => 'imv',
		'title' => 'Imeem (Video)',
		'website' => 'http://www.imeem.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => '(http://media\.imeem\.com/v/(?:[0-9a-z_-]{10}))',
		'embed-movie' => '$2/aus=false/',
		'embed-width' => '400',
		'embed-height' => '271',
	),
	array(
		'id' => 'ima',
		'title' => 'ImageShack',
		'website' => 'http://www.imageshack.us',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://img([0-9]{1,5})\.imageshack\.us/(?:my\.php\?image=|img(?:[0-9]{1,5})/(?:[0-9]{1,8})/|flvplayer\.swf\?f=T)([a-z0-9-_]{1,20})\.flv',
		'embed-movie' => 'http://img$2.imageshack.us/flvplayer.swf?f=T$3&autostart=false',
		'embed-width' => '424',
		'embed-height' => '338',
	),
	array(
		'id' => 'ind',
		'title' => 'IndyaRocks',
		'website' => 'http://www.indyarocks.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?indyarocks\.com/videos/(?:(?:(?:(?:[^-"]*?)-){1,10})|embed-)([0-9]{1,8})',
		'embed-movie' => 'http://www.indyarocks.com/videos/embed-$2',
		'embed-width' => '425',
		'embed-height' => '350',
	),
	array(
		'id' => 'izl',
		'title' => 'Izlesene',
		'website' => 'http://www.izlesene.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?izlesene\.com/(?:player2\.swf\?video=|video/(?:[a-z0-9-_]*?)/)([0-9]{1,10})',
		'embed-movie' => 'http://www.izlesene.com/player2.swf?video=$2',
		'embed-width' => '425',
		'embed-height' => '355',
	),
	array(
		'id' => 'jam',
		'title' => 'Jamendo',
		'website' => 'http://www.jamendo.com',
		'type' => 'audio',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|widgets\.)?jamendo\.com/(?:[a-z0-9]*?)/album/(?:\?album_id=)?([0-9]{1,10})',
		'embed-movie' => 'http://widgets.jamendo.com/en/album/?album_id=$2&playertype=2008',
		'embed-width' => '200',
		'embed-height' => '300',
	),
	array(
		'id' => 'jok',
		'title' => 'Jokeroo',
		'website' => 'http://www.jokeroo.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?jokeroo\.com/(auto|educational|financial|health|howto|lawyers|politics|travel|extremesports|funnyvideos)/((?:(?:[0-9a-z]*?)/){0,3})?([0-9a-z_]*?)\.htm',
		'embed-movie' => 'http://www.jokeroo.com/promotional_player2.swf?channel&vid=http://uploads.filecabin.com/flash/$4.flv&vid_url=http://www.jokeroo.com/$2/$3$4.html&adv_url',
		'embed-width' => '490',
		'embed-height' => '425',
	),
	array(
		'id' => 'jub',
		'title' => 'Jubii Tv',
		'website' => 'http://tv.jubii.co.uk',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|tv\.)?jubii.co\.uk/(?:video/|p/en/)([0-9a-z_-]{10,14})\.html',
		'embed-movie' => 'http://tv.jubii.co.uk/p/en/$2.html',
		'embed-width' => '400',
		'embed-height' => '368',
	),
	array(
		'id' => 'juv',
		'title' => 'JujuNation Video',
		'website' => 'http://www.jujunation.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?jujunation.com/viewVideo\.php\?video_id=([0-9]{1,10})',
		'embed-movie' => 'http://www.jujunation.com/flvplayer.swf?config=http://www.jujunation.com/videoConfigXmlCode.php?pg=video_$2_no_0',
		'embed-width' => '450',
		'embed-height' => '370',
	),
	array(
		'id' => 'jua',
		'title' => 'JujuNation Audio',
		'website' => 'http://www.jujunation.com',
		'type' => 'audio',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?jujunation.com/music\.php\?music_id=([0-9]{1,10})',
		'embed-movie' => 'http://www.jujunation.com/player.swf?configXmlPath=http://www.jujunation.com/musicConfigXmlCode.php?pg=music_$2&playListXmlPath=http://www.jujunation.com/musicPlaylistXmlCode.php?pg=music_$2',
		'embed-width' => '220',
		'embed-height' => '66',
	),
	array(
		'id' => 'jmp',
		'title' => 'JumpCut',
		'website' => 'http://www.jumpcut.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?jumpcut\.com/(?:view(?:/)?|media/flash/jump\.swf)\?id=([0-9a-f]{32})',
		'embed-movie' => 'http://www.jumpcut.com/media/flash/jump.swf?id=$2&asset_type=movie&asset_id=$2&eb=1',
		'embed-width' => '408',
		'embed-height' => '324',
	),
	array(
		'id' => 'justin',
		'title' => 'JustinTV',
		'website' => 'http://www.justin.tv',
		'type' => 'video',
		'added' => '5.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:\w{0,3}\.)?justin\.tv/(\w*)',
		'embed-movie' => 'http://www.justin.tv/widgets/jtv_player.swf?channel=$2&auto_play=false',
		'embed-width' => '353',
		'embed-height' => '295',
	),
	array(
		'id' => 'kew',
		'title' => 'Kewego',
		'website' => 'http://www.kewego.co.uk',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?kewego\.co\.uk/video/([0-9a-z]{12})\.html',
		'embed-movie' => 'http://www.kewego.com/swf/p3/epix.swf?language_code=en&playerKey=09d651125dab&skinKey=71703ed5cea1&sig=$2&autostart=false',
		'embed-width' => '400',
		'embed-height' => '300',
	),
	array(
		'id' => 'kor',
		'title' => 'Koreus',
		'website' => 'http://www.koreus.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?koreus\.com/video/([0-9a-z-]{1,50})(?:\.html)?',
		'embed-movie' => 'http://www.koreus.com/video/$2',
		'embed-width' => '400',
		'embed-height' => '320',
	),
	array(
		'id' => 'laa',
		'title' => 'Last.fm (Audio)',
		'website' => 'http://www.last.fm',
		'type' => 'audio',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?last\.fm/music/([0-9a-z\+_-]*?)/_/([0-9\+a-z_-]*)',
		'embed-movie' => 'http://cdn.last.fm/webclient/s12n/102/lfmPlayer.swf?lang=en&lfmMode=playlist&resname=$3&restype=track&artist=$2&autostart=false',
		'embed-width' => '340',
		'embed-height' => '289',
	),
	array(
		'id' => 'lav',
		'title' => 'Last.fm (Videos)',
		'website' => 'http://www.last.fm',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?last\.fm/music/([0-9a-z\+_-]*?)/\+videos/([0-9\+a-z_-]{2,20})',
		'embed-movie' => 'http://cdn.last.fm/videoplayer/33/VideoPlayer.swf?title=$2&uniqueName=$3&autoStart=false',
		'embed-width' => '340',
		'embed-height' => '289',
	),
	array(
		'id' => 'lib',
		'title' => 'Libero',
		'website' => 'http://www.libero.it',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://video\.libero\.it/app/play(?:/index.html)?\?(?:[^"]*?)?id=([a-f0-9]{32})',
		'embed-movie' => 'http://video.libero.it/static/swf/eltvplayer.swf?id=$2.flv&ap=0',
		'embed-width' => '400',
		'embed-height' => '333',
	),
	array(
		'id' => 'liv',
		'title' => 'LiveLeak',
		'website' => 'http://www.liveleak.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?liveleak\.com/(?:player.swf?autostart=false&(?:amp;)?token=|view\?(?:[^"]*?)?i=|e/)((?:[0-9a-z]{3})_(?:[a-z0-9]{10}))',
		'embed-movie' => 'http://www.liveleak.com/player.swf?autostart=false&token=$2',
		'embed-width' => '450',
		'embed-height' => '370',
	),
	array(
		'id' => 'lvv',
		'title' => 'LiveVideo',
		'website' => 'http://www.livevideo.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?livevideo\.com/(?:flvplayer/embed/|video/(?:view/)?(?:(?:[^"]*?)?/)?)([0-9a-f]{32})',
		'embed-movie' => 'http://www.livevideo.com/flvplayer/embed/$2',
		'embed-width' => '445',
		'embed-height' => '369',
	),
	array(
		'id' => 'mac',
		'title' => 'Machinima (Old)',
		'website' => 'http://www.machinima.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?machinima\.com/(?:film/view&(?:amp;)?id=|#details_)([0-9]{1,8})(?:_contents)?',
		'embed-movie' => 'http://www.machinima.com/_flash_media_player/mediaplayer.swf?file=http://machinima.com/p/$2',
		'embed-width' => '400',
		'embed-height' => '300',
	),
	array(
		'id' => 'man',
		'title' => 'Machinima (New)',
		'website' => 'http://www.machinima.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?machinima\.com:80/f/([0-9a-f]{32})',
		'embed-movie' => 'http://machinima.com:80/_flash_media_player/mediaplayer.swf?file=http://machinima.com:80/f/$2',
		'embed-width' => '400',
		'embed-height' => '300',
	),
	array(
		'id' => 'mai',
		'title' => 'Video.mail.ru',
		'website' => 'http://video.mail.ru',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://video\.mail\.ru/mail/([0-9a-z_-]*?)/([0-9]{1,4})/([0-9]{1,4})\.html',
		'embed-movie' => 'http://img.mail.ru/r/video2/player_v2.swf?par=http://content.video.mail.ru/mail/$2/$3/\$$4&page=1&username=$2&albumid=$3&id=$4',
		'embed-width' => '452',
		'embed-height' => '385',
	),
	array(
		'id' => 'mil',
		'title' => 'Milliyet',
		'website' => 'http://video.milliyet.com.tr',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(http://video\.milliyet\.com\.tr/m\.swf\?id=(?:[0-9]{1,12})&(?:amp;)?tarih=(?:[0-9]{4})/(?:[0-9]{2})/(?:[0-9]{1,2}))',
		'embed-movie' => '$2',
		'embed-width' => '340',
		'embed-height' => '325',
	),
	array(
		'id' => 'mof',
		'title' => 'MoFile',
		'website' => 'http://www.mofile.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|tv\.)?mofile\.com/([0-9a-z]{8})',
		'embed-movie' => 'http://tv.mofile.com/cn/xplayer.swf?v=$2',
		'embed-width' => '480',
		'embed-height' => '409',
	),
	array(
		'id' => 'mot',
		'title' => 'MotionBox',
		'website' => 'http://www.motionbox.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?motionbox\.com/videos/([0-9a-f]{14})',
		'embed-movie' => 'http://www.motionbox.com/external/hd_player/type%3Dsd%2Cvideo_uid%3D$2',
		'embed-width' => '416',
		'embed-height' => '312',
	),
	array(
		'id' => 'mpo',
		'title' => 'Mpora',
		'website' => 'http://video.mpora.com',
		'type' => 'video',
		'added' => '5.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://video\.mpora\.com/watch/(\w{9})',
		'embed-movie' => 'http://video.mpora.com/ep/$2/',
		'embed-width' => '425',
		'embed-height' => '350',
	),
	array(
		'id' => 'mpotv',
		'title' => 'Mpora TV',
		'website' => 'http://tv.mpora.com',
		'type' => 'video',
		'added' => '5.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://tv\.mpora\.com/watch/(\w{9})',
		'embed-movie' => 'http://tv.mpora.com/ep/$2/vod/',
		'embed-width' => '480',
		'embed-height' => '309',
  ),
	array(
		'id' => 'mpt',
		'title' => 'Mp3tube',
		'website' => 'http://www.mp3tube.net',
		'type' => 'audio',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?mp3tube\.net\/play\.swf\?id=(?:[0-9a-f]{32}))',
		'embed-movie' => '$2',
		'embed-width' => '260',
		'embed-height' => '60',
	),
	array(
		'id' => 'msn',
		'title' => 'MSN Live/Soapbox',
		'website' => 'http://video.msn.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(soapbox|video)\.msn\.com/(?:video\.aspx)?\?(mkt=[a-z-]{2,7}&(?:amp;)?)?(?:(?:[^"]*?)vid=|(?:from=msnvideo&(?:amp;)?showPlaylist=true&(?:amp;)?)?playlist=videoByUuids:uuids:)([0-9a-f-]{8,36})',
		'embed-movie' => 'http://images.$2.msn.com/flash/soapbox1_1.swf?$3ch=&c=v&v=$4&title=false&ifs=true&ad=false',
		'embed-width' => '432',
		'embed-height' => '364',
	),
	array(
		'id' => 'mtv',
		'title' => 'MtvU (Usa Only)',
		'website' => 'http://www.mtvu.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?mtvu\.com/video/\?id=([0-9]{1,9})(?:[^"]*?)vid=([0-9]{1,9})',
		'embed-movie' => 'http://www.mtvu.com/player/embed/?CONFIG_URL=http://www.mtvu.com/player/embed/configuration.jhtml%3Fid%3D$2%26vid%3D$3',
		'embed-width' => '423',
		'embed-height' => '318',
	),
	array(
		'id' => 'mus',
		'title' => 'MusOpen',
		'website' => 'http://www.musopen.com',
		'type' => 'audio',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?musopensource\.com/files/([^"\'\`\<\>\@\*\$]*?)\.mp3',
		'embed-movie' => 'http://www.musopen.com/wimpy_button.swf?theFile=http://www.musopensource.com/files/$2.mp3',
		'embed-width' => '35',
		'embed-height' => '35',
		'embed-html-before' => '<div style="border:1px solid #808080;background-color:white;width:350px;text-align:center"><a href="http://www.musopen.com"><img width="89px" height="25px" src="http://www.musopen.com/images/musopen_v.png" alt="" /></a> ',
		'embed-html-after' => '<br />$2</div>', // Since it justs a button we're making a box for it.
	),
	array(
		'id' => 'myn',
		'title' => 'MyNet',
		'website' => 'http://video.eksenim.mynet.com/',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://video\.eksenim\.mynet\.com/(?:[0-9a-z_-]*?)/(?:[0-9a-z_-]*?)/([0-9]{1,12})/',
		'embed-movie' => 'http://video.eksenim.mynet.com/flvplayers/vplayer9.swf?videolist=http://video.eksenim.mynet.com/batch/video_xml_embed.php?video_id=$2',
		'embed-width' => '400',
		'embed-height' => '334',
	),
	array(
		'id' => 'mys',
		'title' => 'MySoccerMedia',
		'website' => 'http://www.mysoccermedia.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?mysoccermedia\.com/videos/(?:[0-9a-f]{14,16})\.flv)',
		'embed-movie' => 'http://mysoccermedia.com/soccer_pl2_playBt.swf?video_flv=$2',
		'embed-width' => '443',
		'embed-height' => '310',
	),
	array(
		'id' => 'myc',
		'title' => 'MyShows.cn/SeeHaha.com',
		'website' => 'http://www.myshows.cn',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://www\.seehaha\.com/flash/player\.swf\?vidFileName=(?:[0-9]*?)\.flv)',
		'embed-movie' => '$2',
		'embed-width' => '425',
		'embed-height' => '350',
	),
	array(
		'id' => 'myt',
		'title' => 'MySpaceTv',
		'website' => 'http://www.myspacetv.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:vids\.myspace|myspacetv)\.com/index\.cfm\?(?:[^"]*?)?VideoID=([0-9]{1,10})',
		'embed-movie' => 'http://mediaservices.myspace.com/services/media/embed.aspx/m=$2',
		'embed-width' => '425',
		'embed-height' => '360',
	),
	array(
		'id' => 'myv',
		'title' => 'MyVideo',
		'website' => 'http://www.myvideo.de',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?myvideo\.(at|be|ch|de|nl)/(?:watch|movie)/([0-9]{1,8})',
		'embed-movie' => 'http://www.myvideo.$2/movie/$3',
		'embed-width' => '470',
		'embed-height' => '406',
	),
	array(
		'id' => 'myi',
		'title' => 'MyVi',
		'website' => 'http://myvi.ru',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?myvi\.ru/ru/flash/player/(?:[0-9a-z_-]{45}))',
		'embed-movie' => '$2',
		'embed-width' => '450',
		'embed-height' => '418',
	),
	array(
		'id' => 'mth',
		'title' => 'M Thai',
		'website' => 'http://video.mthai.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://video\.mthai\.com/player\.php\?(?:[^"]*?)?id=([0-9a-z]{14,20})',
		'embed-movie' => 'http://video.mthai.com/Flash_player/player.swf?idMovie=$2',
		'embed-width' => '407',
		'embed-height' => '342',
	),
	array(
		'id' => 'new',
		'title' => 'NewGrounds',
		'website' => 'http://www.newgrounds.com',
		'type' => 'other',
		'plugin' => 'flash',
  	'embed-pattern' => '(http://uploads\.ungrounded\.net/(?:[0-9]{1,12})/(?:[0-9]{1,12})_(?:[0-9a-z_-]*?)\.swf)',
		'embed-movie' => '$2?autostart=false&autoplay=false',
		'embed-width' => '480',
		'embed-height' => '400',
),
	array(
		'id' => 'nha',
		'title' => 'NhacCuaTui',
		'website' => 'http://www.nhaccuatui.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?nhaccuatui\.com/(?:nghe\?M=|m/)([a-z0-9-_]{10})',
		'embed-movie' => 'http://www.nhaccuatui.com/m/$2',
		'embed-width' => '300',
		'embed-height' => '270',
	),
	array(
		'id' => 'ons',
		'title' => 'OnSmash',
		'website' => 'http://www.onsmash.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|videos\.)?onsmash\.com/(?:v|e)/([0-9a-z]{16})',
		'embed-movie' => 'http://videos.onsmash.com/e/$2',
		'embed-width' => '448',
		'embed-height' => '374',
  ),
	array(
		'id' => 'orb',
		'title' => 'Orb',
		'website' => 'http://www.orb.com',
		'type' => 'other',
		'plugin' => 'flash',
		'embed-pattern' => 'http://mycast\.orb\.com/orb/html/qs\?mediumId=([0-9a-z]{8})&(?:amp;)?l=([0-9a-z_-]{1,20})',
		'embed-movie' => 'http://mycast.orb.com/orb/resources/common/videoplayer.swf?file=http%3A%2F%2Fmycast.orb.com%2Forb%2Fxml%2Fstream%3FstreamFormat%3Dswf%26mediumId%3D$2%26l%3D$3&showdigits=true&autostart=false&shuffle=false&showeq=true&showfsbutton=true',
		'embed-width' => '439',
		'embed-height' => '350',
	),
	array(
		'id' => 'passin',
		'title' => 'Passionato (Single Preview)',
		'website' => 'http://www.passionato.com',
		'type' => 'audio',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)passionato\.com/play/track/([0-9]{1,12})',
		'embed-movie' => 'http://www.passionato.com/swf/media.swf?file=http://www.passionato.com%2Fxspf%2Fplay.php%3FTRACK_ID%3D$2&autostart=false&searchbar=false&showeq=false&displayheight=200&height=200&width=420&backcolor=0x000000&frontcolor=0xCC0000&screencolor=0x000000&lightcolor=0xFFD5D5&overstretch=none&thumbsinplaylist=false&autoscroll=false',
		'embed-width' => '420',
		'embed-height' => '200',
	),
	array(
		'id' => 'pasplay',
		'title' => 'Passionato (Playlist Preview)',
		'website' => 'http://www.passionato.com',
		'type' => 'audio',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)passionato\.com/(?:play/)?release/([0-9]{1,12})',
		'embed-movie' => 'http://www.passionato.com/swf/media.swf?file=http://www.passionato.com%2Fxspf%2Fplay.php%3FALBUM_ID%3D$2&autostart=false&searchbar=false&showeq=false&displayheight=200&height=400&width=420&backcolor=0x000000&frontcolor=0xCC0000&screencolor=0x000000&lightcolor=0xFFD5D5&overstretch=none&thumbsinplaylist=false&autoscroll=false',
		'embed-width' => '420',
		'embed-height' => '400',
	),
	array(
		'id' => 'pho',
		'title' => 'Photobucket',
		'website' => 'http://www.photobucket.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://s(\w{1,5})\.photobucket\.com/albums/((?:(?:[\%0-9a-z_-]{1,50})/){1,10})(?:\?(?:[^"]*?)current=)?([\%0-9a-z_-]{1,50})\.flv',
		'embed-movie' => 'http://www.photobucket.com/player.swf?file=http://vid$2.photobucket.com/albums/$3$4.flv',
		'embed-width' => '448',
		'embed-height' => '361',
	),
	array(
		'id' => 'pik',
		'title' => 'PikNikTube',
		'website' => 'http://www.pikniktube.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?pikniktube\.com/(?:v/|(?:(?:[^"]*?)\?q=))([0-9a-f]{32})',
		'embed-movie' => 'http://www.pikniktube.com/player/videoplayer2.swf?linktarget=_blank&embedded=1&xmlsrc=http://www.pikniktube.com/getxmle.asp?q=$2&a=1&c=0',
		'embed-width' => '340',
		'embed-height' => '320',
	),
	array(
		'id' => 'pro',
		'title' => 'Project Playlist',
		'website' => 'http://www.playlist.com',
		'type' => 'audio',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?playlist\.com/(?:standalone|node)/([0-9]{1,10})',
		'embed-movie' => 'http://www.playlist.com/media/mp3player-standalone.swf?playlist_url=http://www.playlist.com/node/$2/playlist/xspf&config=http://www.musiclist.us/mc/config/config_black.xml&mywidth=435',
		'embed-width' => '435',
		'embed-height' => '270',
	),
	array(
		'id' => 'put',
		'title' => 'Putfile',
		'website' => 'http://www.putfile.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|media\.|feat\.)?putfile\.com/(?:flow/putfile\.swf\?videoFile=|)?([a-z0-9-_]*)(?:\?)?',
		'embed-movie' => 'http://feat.putfile.com/flow/putfile.swf?videoFile=$2',
		'embed-width' => '425',
		'embed-height' => '345',
	),
	array(
		'id' => 'ram',
		'title' => 'Rambler',
		'website' => 'http://vision.rambler.ru',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://vision\.rambler\.ru/(?:i/e\.swf\?id=|users/)((?:[0-9a-z_-]*?)/(?:[0-9]*?)/(?:[0-9]*))',
		'embed-movie' => 'http://vision.rambler.ru/i/e.swf?id=$2&logo=1',
		'embed-width' => '390',
		'embed-height' => '370',
	),
	array(
		'id' => 'raw',
		'title' => 'RawVegas',
		'website' => 'http://www.rawvegas.tv',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?rawvegas\.tv/watch\.php\?vID=([0-9a-f]{30})',
		'embed-movie' => 'http://www.rawvegas.tv/ext.php?uniqueVidID=$2',
		'embed-width' => '427',
		'embed-height' => '300',
	),
	array(
		'id' => 'rut',
		'title' => 'RuTube',
		'website' => 'http://www.rutube.ru',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|video\.)?rutube\.ru/(?:tracks/\d+?\.html\?(?:(?:pos|related)=1&(?:amp;)?)?v=)?([0-9a-f]{32})',
		'embed-movie' => 'http://video.rutube.ru/$2',
		'embed-width' => '470',
		'embed-height' => '353',
	),
	array(
		'id' => 'see',
		'title' => 'Seeqpod',
		'website' => 'http://www.seeqpod.com',
		'type' => 'audio',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?seeqpod\.(?:com|net)/search/\?plid=([0-9a-f]{10})',
		'embed-movie' => 'http://www.seeqpod.net/cache/seeqpodSlimlineEmbed.swf?domain=http://www.seeqpod.com&playlistXMLPath=http://www.seeqpod.com/api/music/getPlaylist?playlist_id=$2',
		'embed-width' => '300',
		'embed-height' => '80',
	),
	array(
		'id' => 'sev',
		'title' => 'SevenLoad',
		'website' => 'http://www.sevenload.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://((?:en|tr|de|www)\.)?sevenload\.com/(?:videos|videolar)/([0-9a-z]{1,8})',
		'embed-movie' => 'http://$2sevenload.com/pl/$3/425x350/swf',
		'embed-width' => '425',
		'embed-height' => '350',
	),
	array(
		'id' => 'shavi',
		'title' => 'ShareView',
		'website' => 'http://www.shareview.us',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?shareview\.us/view/([0-9]{1,10})/',
		'embed-movie' => 'http://www.shareview.us/player/player.swf?file=http://www.shareview.us/flvideo/$2.flv&image=http://www.shareview.us/thumb/$2.jpg&logo=http://www.shareview.us/templates/images/watermark.gif&link=http://www.shareview.us',
		'embed-width' => '425',
		'embed-height' => '350',
	),
	array(
		'id' => 'shark',
		'title' => 'Sharkle',
		'website' => 'http://www.sharkle.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?sharkle\.com/externalPlayer/(?:(?:(?:[0-9a-z]{1,25})/){3}))',
		'embed-movie' => '$2',
		'embed-width' => '340',
		'embed-height' => '310',
	),
	array(
		'id' => 'smo',
		'title' => 'Smotri',
		'website' => 'http://www.smotri.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?smotri\.com/video/view/\?id=v([0-9a-f]{10})',
		'embed-movie' => 'http://pics.smotri.com/scrubber_custom8.swf?file=v$2&bufferTime=3&autoStart=false&str_lang=eng&xmlsource=http%3A%2F%2Fpics.smotri.com%2Fcskins%2Fblue%2Fskin_color_lightaqua.xml&xmldatasource=http%3A%2F%2Fpics.smotri.com%2Fskin_ng.xml',
		'embed-width' => '400',
		'embed-height' => '330',
	),
	array(
		'id' => 'sno',
		'title' => 'Snotr',
		'website' => 'http://www.snotr.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|videos\.)?snotr\.com/(?:player\.swf\?video=|)?(?:video|embed)/([0-9]{1,8})',
		'embed-movie' => 'http://videos.snotr.com/player.swf?video=$2&amp;embedded=true&amp;autoplay=false',
		'embed-width' => '400',
		'embed-height' => '330',
	),
	array(
		'id' => 'sou',
		'title' => 'SouthPark Studios',
		'website' => 'http://www.southparkstudios.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?southparkstudios\.com/clips/([0-9]{1,10})',
		'embed-movie' => 'http://media.mtvnservices.com/mgid:cms:item:southparkstudios.com:$2:',
		'embed-width' => '480',
		'embed-height' => '360',
	),
	array(
		'id' => 'spa',
		'title' => 'Space.tv.cctv.com',
		'website' => 'http://space.tv.cctv.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://((?:(?:[a-z0-9]{1,10})\.){0,2})?cctv\.com/act/video\.jsp\?videoId=VIDE([0-9]{16})',
		'embed-movie' => 'http://$2cctv.com/playcfg/player_new.swf?id=VIDE$3&site=http://$2cctv.com&method=http',
		'embed-width' => '500',
		'embed-height' => '400',
	),
	array(
		'id' => 'spi',
		'title' => 'Spike',
		'website' => 'http://www.spike.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?spike\.com/(?:video/(?:[0-9a-z_-]{2,30})?/|efp\?flvbaseclip=)([0-9]{4,12})',
		'embed-movie' => 'http://www.spike.com/efp?flvbaseclip=$2&',
		'embed-width' => '448',
		'embed-height' => '365',
	),
	array(
		'id' => 'son',
		'title' => 'Songza',
		'website' => 'http://www.songza.com',
		'type' => 'audio',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?songza\.com/e/listen\?(?:zName=(?:[0-9a-z_\%-]*?)&(?:amp;)?)?zId=(?:[0-9a-z_-]{16}))',
		'embed-movie' => '$2&zAutostart=false&zType=flv',
		'embed-width' => '425',
		'embed-height' => '114',
	),
	array(
		'id' => 'spo',
		'title' => 'SportsLine (CBS Sports)',
		'website' => 'http://www.sportsline.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?sportsline\.com/video/player/(?:play|embed)/((?:[a-z0-9]*?)/([0-9a-z_-]{32}))',
		'embed-movie' => 'http://www.cbs.com/thunder/swf30can10cbssports/rcpHolderCbs-3-4x3.swf?link=http://www.sportsline.com/video/player/play/$2&releaseURL=http://release.theplatform.com/content.select?pid=$3&amp;Tracking=true&amp;Embedded=True&autoPlayVid=false',
		'embed-width' => '497',
		'embed-height' => '379',
	),
	array(
		'id' => 'str',
		'title' => 'Streetfire',
		'website' => 'http://www.streetfire.net',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|videos\.)?streetfire\.net/video/((?:[0-9a-z]{8})(?:(?:-(?:[0-9a-z]{4})){3})-(?:[0-9a-z]{12}))\.htm',
		'embed-movie' => 'http://videos.streetfire.net/vidiac.swf?video=$2',
		'embed-width' => '428',
		'embed-height' => '352',
	),
	array(
		'id' => 'stu',
		'title' => 'StupidVideos',
		'website' => 'http://www.stupidvideos.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|images\.)?stupidvideos\.com/(?:video/(?:[^"\#]*?)\#|images/player/player\.swf\?sa=1&(?:amp;)?sk=7&(?:amp;)?si=2&(?:amp;)?i=)([0-9]{1,10})',
		'embed-movie' => 'http://images.stupidvideos.com/images/player/player.swf?sa=1&amp;sk=7&amp;si=2&amp;i=$2',
		'embed-width' => '451',
		'embed-height' => '433',
	),
	array(
		'id' => 'tag',
		'title' => 'TagTélé',
		'website' => 'http://www.tagtele.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://www\.tagtele\.com/(?:v/|videos/voir/)([0-9]{1,12})',
		'embed-movie' => 'http://www.tagtele.com/v/$2',
		'embed-width' => '425',
		'embed-height' => '350',
	),
	array(
		'id' => 'tin',
		'title' => 'TinyPic',
		'website' => 'http://www.tinypic.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?tinypic\.com/player\.php\?v=([0-9a-z-]{1,12})',
		'embed-movie' => 'http://v3.tinypic.com/player.swf?file=$2',
		'embed-width' => '440',
		'embed-height' => '420',
	),
	array(
		'id' => 'tmt',
		'title' => 'Tm-Tube',
		'website' => 'http://www.tm-tube.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?tm-tube\.com/video/([0-9]{1,12})/',
		'embed-movie' => 'http://www.tm-tube.com/flvplayer.swf?mediaid=$2&hosturl=http://www.tm-tube.com/&themecolor=0x696969&symbolcolor=0xb22222&backgroundcolor=0x000000&autostart=false&loop=false&overlay=http://www.tm-tube.com//media/custom/player_emb.png&&',
		'embed-width' => '480',
		'embed-height' => '360',
	),
	array(
		'id' => 'tra',
		'title' => 'TrailerAddict',
		'website' => 'http://www.traileraddict.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?traileraddict\.com/emb/(?:[0-9]{1,10}))',
		'embed-movie' => '$2',
		'embed-width' => '520',
		'embed-height' => '317',
	),
	array(
		'id' => 'trt',
		'title' => 'TrTube',
		'website' => 'http://www.trtube.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?trtube\.com/mediaplayer_(?:[0-9]{1,2})_(?:[0-9]{1,2})\.swf\?file=http://(?:www\.)?trtube\.com/vid(?:[0-9]{1,2})?/(?:[0-9]{1,10}).flv)',
		'embed-movie' => '$2',
		'embed-width' => '425',
		'embed-height' => '350',
	),
	array(
		'id' => 'tru',
		'title' => 'Trilulilu',
		'website' => 'http://www.trilulilu.ro',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?trilulilu\.ro/([0-9a-z_-]*?)/([0-9a-f]{14})',
		'embed-movie' => 'http://www.trilulilu.ro/embed/flash.php?type=video&amp;hash=$3&userid=$2',
		'embed-width' => '440',
		'embed-height' => '362',
	),
	array(
		'id' => 'tut',
		'title' => 'Tu',
		'website' => 'http://www.tu.tv',
		'type' => 'video',
		'plugin' => 'flash',
		'title' => 'Tu.tv',
		'embed-pattern' => '(http://tu\.tv/tutvweb\.swf\?xtp=(?:[0-9]{1,10}))',
		'embed-movie' => '$2',
		'embed-width' => '425',
		'embed-height' => '350',
	),
	array(
		'id' => 'tud',
		'title' => 'Tudou',
		'website' => 'http://www.tudou.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?tudou\.com/(?:programs/view/|v/)([a-z0-9-]{1,12})',
		'embed-movie' => 'http://www.tudou.com/v/$2',
		'embed-width' => '400',
		'embed-height' => '300',
	),
	array(
		'id' => 'uov',
		'title' => 'UOL VideoLog',
		'website' => 'http://videolog.uol.com.br',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://videolog\.uol\.com\.br/video(?:\?|\.php\?id=)([0-9]{1,9})',
		'embed-movie' => 'http://www.videolog.tv/swfs/externo_api.swf?v=$2&amp;id_video=$2',
		'embed-width' => '512',
		'embed-height' => '384',
	),
	array(
		'id' => 'uum',
		'title' => 'UUME',
		'website' => 'http://www.uume.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|pic\.)?uume\.com/play_([a-z0-9]{12})',
		'embed-movie' => 'http://www.uume.com/v/$2_UUME',
		'embed-width' => '400',
		'embed-height' => '342',
	),
	array(
		'id' => 'utu',
		'title' => 'u-Tube',
		'website' => 'http://www.u-tube.ru',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?u-tube\.ru/(?:playlist\.php\?id=|pages/video/)([0-9]{1,12})',
		'embed-movie' => 'http://www.u-tube.ru/upload/others/flvplayer.swf?file=http://www.u-tube.ru/playlist.php?id=$2&width=400&height=300',
		'embed-width' => '400',
		'embed-height' => '300',
	),
	array(
		'id' => 'vij',
		'title' => 'VideoJug',
		'website' => 'http://www.videojug.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)videojug\.com/film/player\?id=(?:[0-9a-z]{8})(?:(?:-(?:[0-9a-z]{4})){3})-(?:[0-9a-z]{12}))',
		'embed-movie' => '$2',
		'embed-width' => '400',
		'embed-height' => '345',
	),
	array(
		'id' => 'sap',
		'title' => 'videos.sapo',
		'website' => 'http://videos.sapo.pt',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(www\.|(?:(?:(?:[0-9a-z]{3,12})\.){1,2}))?sapo\.pt/([0-9a-z]{20})',
		'embed-movie' => 'http://$2sapo.pt/play?file=http://$2sapo.pt/$3/mov/1',
		'embed-width' => '400',
		'embed-height' => '322',
	),
	array(
		'id' => 'vic',
		'title' => 'Vidiac',
		'website' => 'http://www.vidiac.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?vidiac\.com/video/((?:[0-9a-z]{8})(?:(?:-(?:[0-9a-z]{4})){3})-(?:[0-9a-z]{12}))\.htm',
		'embed-movie' => 'http://www.vidiac.com/vidiac.swf?video=$2',
		'embed-width' => '428',
		'embed-height' => '352',
	),
	array(
		'id' => 'vdd',
		'title' => 'Viddler',
		'website' => 'http://www.viddler.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://www\.viddler\.com/(?:player|simple)/(?:[0-9a-f]{8})/)',
		'embed-movie' => '$2',
		'embed-width' => '437',
		'embed-height' => '288',
	),
	array(
		'id' => 'videa',
		'title' => 'Videa',
		'website' => 'http://www.videa.hu',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?videa\.hu/(?:(?:[^"]*)-|flvplayer\.swf\?v=)([0-9a-z]{16})',
		'embed-movie' => 'http://videa.hu/flvplayer.swf?v=$2',
		'embed-width' => '434',
		'embed-height' => '357',
	),
	array(
		'id' => 'vin',
		'title' => 'VideoNuz',
		'website' => 'http://www.videonuz.com',
		'type' => 'video',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?videonuz\.com/videonuz\.swf\?videoLink=video_(?:[0-9a-z]{8,12})\.flv&(?:amp;)?resim=video_([0-9a-z]{8,12})\.(?:jpg|gif))',
		'embed-movie' => '$2',
		'embed-width' => '400',
		'embed-height' => '325',
	),
	array(
		'id' => 'vil',
		'title' => 'VidiLife',
		'website' => 'http://www.vidilife.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?vidilife\.com/flash/flvplayer\.swf\?xml=http://(?:www\.)?vidilife\.com/media/play_flash_xml\.cfm\?id=(?:[0-9a-f]{8})-(?:[0-9a-f]{4})-(?:[0-9a-f]{4})-(?:[0-9a-f]{4})-(?:[0-9a-f]{1}))',
		'embed-movie' => '$2',
		'embed-width' => '445',
		'embed-height' => '363',
	),
	array(
		'id' => 'vim',
		'title' => 'VidMax',
		'website' => 'http://www.vidmax.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(www\.)?vidmax\.com/(?:index\.php/)?videos?/(?:view/)?([0-9]{1,10})',
		'embed-movie' => 'http://$2vidmax.com/player/flvplayer_NOLOGO.swf?file=http://$2vidmax.com/media/video/$3.flv&autostart=false&repeat=false&bufferlength=5&backcolor=0x000000&frontcolor=0xCCCCCC',
		'embed-width' => '400',
		'embed-height' => '300',
	),
	array(
		'id' => 'viv',
		'title' => 'Vidivodo',
		'website' => 'http://www.vidivodo.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://www\.vidivodo\.com/VideoPlayerShare\.swf\?lang=([0-9a-z]*?)&(?:amp;)?vidID=([0-9]*?)&(?:amp;)?vCode=v([0-9]*?)&(?:amp;)?dura=([0-9]*?)&(?:amp;)?File=(?:http://video(?:[0-9]*?)\.vidivodo\.com/)?(vidservers/server(?:[0-9]*?)/videos/(?:[0-9]{4})/(?:[0-9]{2})/(?:[0-9]{2})/(?:[0-9]*?)/v(?:[0-9]*?)\.flv)',
		'embed-movie' => 'http://www.vidivodo.com/VideoPlayerShare.swf?lang=$2&vidID=$3&vCode=v$4&dura=$5&File=$6',
		'embed-width' => '425',
		'embed-height' => '343',
	),
	array(
		'id' => 'voi',
		'title' => 'VoiceThread',
		'website' => 'http://www.voicethread.com',
		'type' => 'other',
		'added' => '4.0',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?voicethread\.com/(?:share/|book\.swf\?b=)([0-9]{1,10})',
		'embed-movie' => 'http://www.voicethread.com/book.swf?b=$2',
		'embed-width' => '480',
		'embed-height' => '360',
	),
	array(
		'id' => 'vso',
		'title' => 'VSocial (Type1)',
		'website' => 'http://www.vsocial.com/vsandbox/',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.|static\.)?vsocial\.com/(?:video/|flash/ups\.swf)\?d=([0-9]{1,8})',
		'embed-movie' => 'http://static.vsocial.com/flash/ups.swf?d=$2&a=0',
		'embed-width' => '410',
		'embed-height' => '400',
	),
	array(
		'id' => 'vsn',
		'title' => 'VSocial (Type2)',
		'website' => 'http://www.vsocial.com/vsandbox/',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => '(http://(?:www\.)?vsocial\.com/ups/(?:[a-f0-9]{32}))',
		'embed-movie' => '$2',
		'embed-width' => '410',
		'embed-height' => '400',
	),
	array(
		'id' => 'weg',
		'title' => 'WeGame',
		'website' => 'http://www.wegame.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?wegame\.com/watch/([0-9a-z_-]*?)/',
		'embed-movie' => 'http://wegame.com/static/flash/player2.swf?tag=$2',
		'embed-width' => '480',
		'embed-height' => '387',
	),
	array(
		'id' => 'wip',
		'title' => 'Wipodo',
		'website' => 'http://www.wipodo.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:www\.)?wipido\.com/(?:profile/)?video/(?:embedconfig/)?([0-9]{1,10})(?:%3Ftemplate%3Dgamersydevideo/)?',
		'embed-movie' => 'http://www.wipido.com/static/wipidotv/mediaplayer.swf?id=$2&file=http://www.wipido.com/uploads/videos/$2_mq.mp4&image=http://www.wipido.com/uploads/videos/$2_screenie.jpg&logo=http://www.wipido.com/images/web/overlay.png&link=http://www.wipido.com/video/$2&linktarget=_blank&backcolor=0x2a2f35&frontcolor=0xffffff&lightcolor=0xff0000&screencolor=0x000000&height=320&width=480',
		'embed-width' => '480',
		'embed-height' => '320',
	),
	array(
		'id' => 'yav',
		'title' => 'Yahoo Video',
		'website' => 'http://video.yahoo.com',
		'type' => 'pop',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:(?:www|uk|fr|it|es|br|au|mx|de|ca)\.)?video\.yahoo\.com/watch/([0-9]{1,12})/([0-9]{1,12})',
		'embed-movie' => 'http://d.yimg.com/static.video.yahoo.com/yep/YV_YEP.swf?ver=2.2.18.2&id=$3&vid=$2&lang=en-us&intl=us',
		'embed-width' => '512',
		'embed-height' => '322',
	),
	array(
		'id' => 'yah',
		'title' => 'Yahoo Video HK',
		'website' => 'http://hk.video.yahoo.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:w\.video\.)?hk\.video\.yahoo\.(?:com|net)/video/(?:dplayer\.html\?vid=|video\.html\?id=)([0-9]{1,10})',
		'embed-movie' => 'http://w.video.hk.yahoo.net/video/dplayer.html?vid=$2',
		'embed-width' => '420',
		'embed-height' => '370',
	),
	array(
		'id' => 'yam',
		'title' => 'Yahoo Music Videos',
		'website' => 'http://music.yahoo.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:new\.)?(?:(?:uk|fr|it|es|br|au|mx|de|ca)\.)?music\.yahoo\.com/(?:[^"]*?)?--([0-9]{1,12})',
		'embed-movie' => 'http://d.yimg.com/cosmos.bcst.yahoo.com/up/fop/embedflv/swf/fop.swf?id=v$2&eID=0000000&lang=us&enableFullScreen=0&shareEnable=1',
		'embed-width' => '400',
		'embed-height' => '255',
	),
	array(
		'id' => 'yku',
		'title' => 'YouKu',
		'website' => 'http://www.youku.com',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:v\.youku\.com/v_show/id_|player\.youku\.com/player\.php/sid/)([0-9a-z]{6,14})',
		'embed-movie' => 'http://player.youku.com/player.php/sid/$2=/v.swf',
		'embed-width' => '450',
		'embed-height' => '372',
	),
	array(
		'id' => 'yvs',
		'title' => 'You.Video.Sina.com.cn',
		'website' => 'http://you.video.sina.com.cn',
		'type' => 'video',
		'plugin' => 'flash',
		'embed-pattern' => 'http://(?:vhead\.blog|you\.video)\.sina\.com\.cn/(?:player/(?:[^"]*?)vid=|b/)([0-9]{5,12})(?:-|&(?:amp;)?uid=)([0-9]{5,12})',
		'embed-movie' => 'http://vhead.blog.sina.com.cn/player/outer_player.swf?auto=0&vid=$2&uid=$3',
		'embed-width' => '480',
		'embed-height' => '370',
	),
);

?>